# Create a namespace
apiVersion: v1
kind: Namespace
metadata:
  name: chat-agents

---

# Deploy a pod in the namespace
apiVersion: v1
kind: Pod
metadata:
  name: alta-ai-pod
  namespace: chat-agents
  labels:
    app: alta-ai-agent
spec:
  containers:
    - name: alta-ai-container
      image: 050752637092.dkr.ecr.us-west-2.amazonaws.com/altaai/eliza-fuss@sha256:cd1de3f45834994e7756b698650b53c09cadbaaa2d1c07fc4e1994dac03c8209
      env:
      - name: FUSS_API_URL
        value: "http://34.209.204.175:8000/chat_with_x_bot_assitant__post"
      - name: FUSS_AGENT_TYPE
        value: "script_writer"
      - name: FUSS_AGENT_ID
        value: "ad759207-a026-08cd-fuss-89fac3000001"
      - name: MONGODB_CONNECTION_STRING
        value: "mongodb://root:password@35.88.132.54:8002/?directConnection=true"
      - name: MONGODB_DATABASE
        value: "fuss_agent"
      - name: TWITTER_DRY_RUN
        value: "false"
      - name: TWITTER_USERNAME
        value: "AltaAI_agent"
      - name: TWITTER_PASSWORD
        value: "Streamkar2025"
      - name: TWITTER_EMAIL
        value: "qia.wang.altatv@gmail.com"
      - name: TWITTER_2FA_SECRET
        value: "H6OT6NUUUNQI7JS2"
      - name: TWITTER_POLL_INTERVAL
        value: "120"
      - name: TWITTER_SEARCH_ENABLE
        value: "false"
      - name: TWITTER_TARGET_USERS
        value: ""
      - name: TWITTER_RETRY_LIMIT
        value: "3"
      - name: TWITTER_SPACES_ENABLE
        value: "false"
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "64Mi"
          cpu: "250m"