apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::050752637092:role/AmazonEKSAutoNodeRole
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - arn:aws:iam::050752637092:user/yang_chen
      username: yang_chen
      groups:
        - system:masters
    - arn:aws:iam::050752637092:user/weiqi_wang
      username: weiqi_wang
      groups:
        - system:masters
