# Deploy a pod in the namespace
apiVersion: apps/v1
kind: Deployment
metadata:
  name: investor-deployment
  namespace: chat-agents
  labels:
    app: investor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: investor
  template:
    metadata:
      labels:
        app: investor
    spec:
      containers:
        - name: investor-container
          image: 050752637092.dkr.ecr.us-west-2.amazonaws.com/altaai/eliza-fuss@sha256:a97d404f26b223dc2ccf0505f9952142836eda4f8e122f9c5bfab51c78d77426
          env:
          - name: FUSS_API_URL
            value: "http://34.209.204.175:8000/chat_with_x_bot_assitant"
          - name: FUSS_AGENT_TYPE
            value: "investor"
          - name: FUSS_AGENT_ID
            value: "ad759207-a026-08cd-fuss-89xxx3000005"
          - name: MONGODB_CONNECTION_STRING
            value: "mongodb://root:mongo3021195@35.88.132.54:8002/?directConnection=true"
          - name: MONGODB_DATABASE
            value: "fuss_agent"
          - name: TWITTER_DRY_RUN
            value: "false"
          - name: TWITTER_USERNAME
            value: "FussInvestor"
          - name: TWITTER_PASSWORD
            value: "Terry123!"
          - name: TWITTER_EMAIL
            value: "x13@thecommonvision.com"
          - name: TWITTER_2FA_SECRET
            value: ""
          - name: TWITTER_POLL_INTERVAL
            value: "120"
          - name: TWITTER_SEARCH_ENABLE
            value: "false"
          - name: TWITTER_TARGET_USERS
            value: ""
          - name: TWITTER_RETRY_LIMIT
            value: "50"
          - name: TWITTER_SPACES_ENABLE
            value: "false"
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "2000Mi"
              cpu: "2000m"
            requests:
              memory: "2000Mi"
              cpu: "2000m"